### ISSUE TITLE
[Bug] mkdocs material 主题下，当页面一级标题使用 `===` 而不是 `#` 来标记时，统计信息会显示错位

### ISSUE THREAD

**Issue by Xiaokang2022** [TonyCrane/mkdocs-statistics-plugin#11]
当使用如下方式来表示一级标题：

```markdown
Title
=====
```

而不是下面这种方式：

```markdown
# Title
```

的时候，统计信息会被渲染到标题的上面去，虽看着没啥问题，但好像又有点问题😅

![image](https://github.com/user-attachments/assets/17bc378f-568c-4e61-83b4-11cba7111143)

正常是这样的：

![image](https://github.com/user-attachments/assets/e1c3c08f-0538-4187-8390-11ac79ba9fa5)

作者修一下吧，虽然我知道规范的 `markdown` 推荐是使用 `#` 而不是 `===`，但奈何以前写的文档就是这样的，太多了不好改。

而且，就算不符合标准规范，这个语法也是没有问题，位置不应该错误。

**Comment by TonyCrane** [comment]
v0.1.3 版本里修了
