### ISSUE TITLE
有没有考虑过增加对页面图片的数量统计？

### ISSUE THREAD

**Issue by Xiaokang2022** [TonyCrane/mkdocs-statistics-plugin#12]
如题

**Comment by TonyCrane** [comment]
这个我个人没有过这个需求，要做的话应该也不复杂（

有人做了的话可以 PR

**Comment by Xiaokang2022** [comment]
@TonyCrane 

> 这个我个人没有过这个需求，要做的话应该也不复杂（
> 
> 有人做了的话可以 PR

我已经 Fork 了这个仓库并提交了一份 PR(https://github.com/TonyCrane/mkdocs-statistics-plugin/pull/18) 实现了这个需求，您看一下下吧

**Comment by TonyCrane** [comment]
closed by #19
