### ISSUE TITLE
[Bug] 当阅读时间少于 1 分钟时会直接不显示阅读时间

### ISSUE THREAD

**Issue by Xiaokang2022** [TonyCrane/mkdocs-statistics-plugin#16]
如题，这是我通过查看源代码发现的问题。

**Comment by Xiaokang2022** [comment]
我已经 Fork 了这个仓库并提交了一份 PR(https://github.com/TonyCrane/mkdocs-statistics-plugin/pull/18) 解决了这个问题

**Comment by Xiaokang2022** [comment]
这个貌似是 templates 的问题

**Comment by TonyCrane** [comment]
closed by #19
