### ISSUE TITLE
页面没有一级标题，但代码块里有单独一行 `#` 注释时，页面统计生成位置出错

### ISSUE THREAD

**Issue by smd1121** [TonyCrane/mkdocs-statistics-plugin#6]
### 描述

代码对页面统计位置的判断逻辑是首个一级标题之后，但是 [这里](https://github.com/TonyCrane/mkdocs-statistics-plugin/blob/a426c1f95613659392960c51f65dfa6671d274a2/mkdocs_statistics_plugin/plugin.py#L116C22-L116C22) 判断一级标题的方式是 `\s*# `

但是如果页面没有一级标题，就会匹配到代码块中的 `#` 注释 ~，请看 VCR~

---

### minimum example 🌰

page src:

````
```python
# xg 你好！
def init():
    print("Hello World")
```
````

效果：

<img width="736" alt="image" src="https://github.com/TonyCrane/mkdocs-statistics-plugin/assets/30610597/b3d4d98e-321a-4dcb-a52f-d201e7f79f24">

---

（Just FYI，根据我的尝试，`#` 前面有空格的话似乎不会被理解成标题？）

**Comment by TonyCrane** [comment]
一个规范的 md 文件要求有且仅有一个一级标题且作为开头，且井号应该作为一行的开始（前面没有空格）。所以有问题的话自己改，写的不规范不惯着。

但 `\s*# ` 是可以匹配 # 前有空格的，我怀疑你是 # 后没加空格（

**Comment by smd1121** [comment]
明白了！我遵从规范🥺
 
抱歉后面那个我没说清楚，其实我想表达的是：如你所说，标题 `#` 应当放在行首，我用 mkdocs 尝试如果 `#` 前面有空格也不会被渲染成标题。所以也许可以把 reg 改成 `# `？

**Comment by TonyCrane** [comment]
> 明白了！我遵从规范🥺
>  
> 抱歉后面那个我没说清楚，其实我想表达的是：如你所说，标题 `#` 应当放在行首，我用 mkdocs 尝试如果 `#` 前面有空格也不会被渲染成标题。所以也许可以把 reg 改成 `# `？

确实可以，不改也行，懒懒
