### ISSUE TITLE
A little suggestion

### ISSUE THREAD

**Issue by Wcowin** [TonyCrane/mkdocs-statistics-plugin#7]
推荐作者参加这个：https://github.com/mkdocs/mkdocs/discussions/3622

我使用了一段时间这个插件 但很遗憾还是弃用了 但是你做的工作是精彩的！
问题：
1.统计过程中发现对于代码的行数统计不是很正确（退出是否和正则表达式规则有关）
2.目前对于MKdocs推出的Blog界面这个插件的显示会有遮挡，我尝试修复失败
这是我使用后的一些感受，但我目前无法提供截图指出上述错误

最后再次感谢作者的努力，如果进一步优化 这个插件会更好~
![](https://private-user-images.githubusercontent.com/99159173/317135247-f47528c6-26f4-418e-a153-f990e4c80ede.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NTkyODUsIm5iZiI6MTcxMjY1ODk4NSwicGF0aCI6Ii85OTE1OTE3My8zMTcxMzUyNDctZjQ3NTI4YzYtMjZmNC00MThlLWExNTMtZjk5MGU0YzgwZWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDEwMzYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkYzJhOGYwMTBjMzhlOGM3NTE0NTE2NjA3NzMxZmNjMWI1ZDkzOWI2YTQ3Yjc1N2Q2MDMzOThlMTM1YjQzYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f6ItE7q45hlBJFEJYihA0_05_E2t0e2-dwAxILPMPfA)

**Comment by TonyCrane** [comment]
有使用问题的话给出复现方法我会修，不然说了也是白说……我也不知道怎么优化
