### ISSUE TITLE
Mkdocs-Material主题启用Blog后显示会错位，且多次添加统计信息

### ISSUE THREAD

**Issue by yanedie** [TonyCrane/mkdocs-statistics-plugin#8]
![image](https://github.com/TonyCrane/mkdocs-statistics-plugin/assets/36914748/fa14e3bd-7c57-470b-a80f-6edf75a429e0)

**Comment by Cdm2883** [comment]
建议自己改模板

**Comment by Xiaokang2022** [comment]
@yanedie 

经测试，只修改模板无法解决该问题。因为 blog 插件在将博客内容搞到索引页的时候会把 `h1` 标签转换为 `h2` 标签，而 `material` 的 `h1` 标签与 `h2` 的样式不一样，两者的 `margin` 不同，前者 `margin-bottom` 有值，导致修改模板无法解决这个问题，因为无法同时适配两个样式。

目前，给出的解决方案如下：

将当前默认模板中关于 `margin` 的部分删除，然后在 `material` 中的 `extra_css` 里添加对 `h1` 的修改：

```css
.md-typeset h1 {
    margin: 0 0;
}
```

这样才能解决这个问题。效果见：<https://xiaokang2022.github.io/tkintertools/blog/>

@TonyCrane 不知关于这个问题，该插件是否能通过添加关于这个的额外的 CSS 文件来解决呢？如果您允许添加额外的 CSS，我很乐意创建一个 PR 来完成这个任务。如果怕破坏或者与原有的 CSS 产生一些冲突，那确实只能让用户自己添加这个 CSS，那这里算是给出了一个解决方案。

**Comment by Xiaokang2022** [comment]
> 如果怕破坏或者与原有的 CSS 产生一些冲突，那确实只能让用户自己添加这个 CSS，那这里算是给出了一个解决方案。

已知可能的冲突：

单页禁用数据统计显示时，标题和内容之间的空行会显著减小，因为这个空行在上述提到的 CSS 中删除了。不过这并不会影响内容的呈现，只是看起来和之前的不同。

**Comment by Cdm2883** [comment]
> 经测试，只修改模板无法解决该问题。因为 blog 插件在将博客内容搞到索引页的时候会把 `h1` 标签转换为 `h2` 标签，而 `material` 的 `h1` 标签与 `h2` 的样式不一样，两者的 `margin` 不同，前者 `margin-bottom` 有值，导致修改模板无法解决这个问题，因为无法同时适配两个样式。
> 

模板能做的很多，改模板确实可以解决问题。我将信息展示的位置换到了 meta，详见：

- [我的博客](https://blog.cdms.vip/2024/10/06/feasibility-study-for-compose-for-harmony/)
- [博客模板](https://github.com/Cdm2883/Blog/blob/3fbfe8d1238103b62e2ff303d87b906e726e2d1e/overrides/blog-post.html)
- [统计模板（本插件）](https://github.com/Cdm2883/Blog/blob/3fbfe8d1238103b62e2ff303d87b906e726e2d1e/overrides/page_statistics.html)

若需使用代码，请遵循仓库 LICENSE 文件

**Comment by Xiaokang2022** [comment]
也算是一种解决方案吧，但这个移动了统计数据原来的位置，和其他普通的文章没有保持一致，比较适合用专门用于博客的站点，而我这种混合的不太适合。
