### ISSUE TITLE
在本地没问题，一到cloudflare上部署就失败

### ISSUE THREAD

**Issue by AlexTYJ** [TonyCrane/mkdocs-statistics-plugin#9]
cloudflare上说：
13:10:01.599 | Aborted with a configuration error!
-- | --
13:10:01.600 | ERROR   -  Config value 'plugins': The "statistics" plugin is not installed
13:10:01.634 | Failed: Error while executing user command. Exited with error code: 1
13:10:01.645 | Failed: build command exited with code: 1
13:10:07.380 | Failed: error occurred while running build command

请问怎么解决呢

**Comment by TonyCrane** [comment]
`Config value 'plugins': The "statistics" plugin is not installed` cloudflare 上没装包？

**Comment by VictorWang712** [comment]
所以请问一下这个应该怎么解决呢？
